lib/pcpb_web/router.ex
defmodule PcpbWeb.Router do
  use PcpbWeb, :router
  use Pow.Phoenix.Router

  use Pow.Extension.Phoenix.Router,
    otp_app: :pcpb,
    extensions: [PowResetPassword, PowPersistentSession]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PcpbWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Pow.Plug.Session, otp_app: :pcpb
    plug PcpbWeb.AssignUser
  end

  pipeline :old_admin do
    plug :put_root_layout, {PcpbWeb.OldAdminView, :layout}
    plug :put_layout, {PcpbWeb.OldAdminView, :live}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler

    plug PcpbWeb.AssignUser
  end

  pipeline :not_authenticated do
    plug Pow.Plug.RequireNotAuthenticated,
      error_handler: PcpbWeb.AuthErrorHandler
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
    pow_extension_routes()
  end

  scope "/", PcpbWeb do
    pipe_through [:browser, :not_authenticated]

    get "/signup", RegistrationController, :new, as: :signup
    post "/signup", RegistrationController, :create, as: :signup
    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
  end

  scope "/", PcpbWeb do
    pipe_through :browser
    live "/", PageLive, :index

  end

  @products [:cpu, :cpu_cooler, :memory, :case, :psu, :gpu, :motherboard, :storage]


  scope "/products", PcpbWeb do
    pipe_through :browser
    live "/", ProductLive.Index, :index
    live "/new", ProductLive.Index, :new
    live "/edit/:id", ProductLive.Show, :edit
    live "/:category", ProductLive.Index, :index
    live "/:category/:id", ProductLive.Show, :index

      # for product <- @products do
      #   live "/#{product}", ProductLive.Index, product
      #   live "/#{product}/:id", ProductLive.Show, String.to_atom("#{product}_show")
      #   live "/#{product}/:id/edit", ProductLive.Index, String.to_atom("#{product}_edit")
      #   live "/#{product}/new", ProductLive.Index, String.to_atom("#{product}_new")
      # end
  end

  scope "/oldadmin", PcpbWeb do
    pipe_through [:browser, :old_admin]

    live "/admin", AdminLive.Index, :index
    live "/admin/parts", AdminLive.Parts.Index, :index

    for part <- @products do
      live "/admin/parts/#{part}", AdminLive.Parts.Part, part
      live "/admin/parts/#{part}/new", AdminLive.Parts.Part, String.to_atom("#{part}_new")
      live "/admin/parts/#{part}/:id", AdminLive.Parts.Part, String.to_atom("#{part}_edit")
    end
  end
end

lib/pcpb_web/views/layout_view.ex
defmodule PcpbWeb.LayoutView do
  use PcpbWeb, :view

  def products_map do
    [
      %{name: "CPU", atom: :cpu, icon: ""},
      %{name: "CPU Cooler", atom: :cpu_cooler, icon: ""},
      %{name: "Case", atom: :case, icon: ""},
      %{name: "Memory", atom: :memory, icon: ""},
      %{name: "Motherboard", atom: :motherboard, icon: ""},
      %{name: "PSU", atom: :psu, icon: ""},
      %{name: "GPU", atom: :gpu, icon: ""},
      %{name: "Storage", atom: :storage, icon: ""},
      %{name: "PSU", atom: :psu, icon: ""}
    ]
  end

  def nav_classes do
    "p-5 hover:bg-red-500 text-pcpbblue hover:text-white no-underline hover:no-underline items-center inline-flex"
  end
end

lib/pcpb_web/templates/layout/app.html.eex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/pcpb_web/templates/layout/live.html copy.leex
<style></style>
<script></script>
<nav class="relative text-gray-900 bg-white border-gray-300"  x-data="{ open: false }">
  <div class="container flex justify-around mx-auto">
    <div class="relative block p-4 text-xl font-bold text-blue-600 lg:p-6">PCPartBuilder</div>
    <ul class="flex">
      <!--Regular Link-->
      <li class="hover:bg-blue-800 hover:text-white">
        <a href="#" class="relative block px-2 py-6 text-sm font-bold lg:p-6 lg:text-base">Normal</a>
      </li>
      <li class="hover:bg-blue-800 hover:text-white"
        @click="open = !open"
        @click.away="open = false"
      >
        <a class="relative block px-2 py-6 text-sm font-bold lg:p-6 lg:text-base"

        >Products</a>
      </li>
      <!--Hoverable Link-->
      <%= if @user do %>
      <li class="">
        <a class="relative block px-4 py-6 text-sm font-bold lg:p-6 lg:text-base hover:bg-blue-800 hover:text-white"><%= @user.email %></a>
      </li>
      <% else %>
      <%= live_patch "Login", to: Routes.login_path(@socket, :new), class: "relative block px-4 py-6 text-sm font-bold lg:p-6 lg:text-base hover:bg-blue-800 hover:text-white" %>
      <%= live_patch "Register", to: Routes.signup_path(@socket, :new), class: "relative block px-4 py-6 text-sm font-bold lg:p-6 lg:text-base hover:bg-blue-800 hover:text-white" %>
      </li>
      <% end %>

    </ul>
  </div>
  <div x-ref="dropdown" x-show="open" class="container p-2 mx-auto mb-16 text-center bg-blue-800 shadow-xl dropdown-menu sm:mb-0">
    <div class="container flex flex-wrap justify-between">
      <ul class="px-4 pt-6 pb-6 border-b border-gray-600 sm:w-1/2 lg:w-1/2 sm:border-r lg:border-b-0 lg:pt-3">
        <h3 class="mb-2 text-xl font-bold text-white text-bold">Heading 1</h3>
        <%= for product <- PcpbWeb.LayoutView.products_map do %>
          <li>
          <%= live_patch product.name , to: Routes.product_index_path(@socket, :index, product.atom), class: "block p-3 text-gray-300 hover:bg-blue-600 hover:text-white" %>
          </li>
        <% end %>
      </ul>
      <ul class="w-full px-4 pt-6 pb-6 border-b border-gray-600 sm:w-1/2 lg:w-1/2 sm:border-r-0 lg:border-r lg:border-b-0 lg:pt-3">
        <h3 class="mb-2 text-xl font-bold text-white text-bold">Heading 2</h3>
        <li>
          <a href="#" class="block p-3 text-gray-300 hover:bg-blue-600 hover:text-white">Category One Sublink</a>
        </li>
        <li>
          <a href="#" class="block p-3 text-gray-300 hover:bg-blue-600 hover:text-white">Category One Sublink</a>
        </li>
        <li>
          <a href="#" class="block p-3 text-gray-300 hover:bg-blue-600 hover:text-white">Category One Sublink</a>
        </li>
        <li>
          <a href="#" class="block p-3 text-gray-300 hover:bg-blue-600 hover:text-white">Category One Sublink</a>
        </li>
        <li>
          <a href="#" class="block p-3 text-gray-300 hover:bg-blue-600 hover:text-white">Category One Sublink</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<main role="main" class="container mx-auto">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>
  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>
  <%= @inner_content %>
</main>




 <nav class="relative text-gray-900 bg-white border-gray-300"  x-data="{ open: false }">
        <div class="container flex mx-auto">
          <div class="flex-1">
            <%= live_patch "PCPartBuilder", to: Routes.page_path(@socket, :index), class: "flex-1" %>
            <%= live_patch "System Builder", to: Routes.product_index_path(@socket, :index), class: "" %>
            <%= live_patch "Products", to: Routes.product_index_path(@socket, :index), class: "" %>
            <ul class="hidden">
              <%= for product <- PcpbWeb.LayoutView.products_map do %>
                <li>
                  <%= live_patch product.name, to: Routes.product_index_path(@socket, :index, product.atom), class: "" %>
                </li>
              <% end %>
            </ul>
          </div>
          <div class="">
            <%= if @user do %>
              <a class=""><%= @user.username %></a>
            <% else %>
              <%= live_patch "Login", to: Routes.login_path(@socket, :new), class: "" %>
              <%= live_patch "Register", to: Routes.signup_path(@socket, :new), class: "" %>
            </li>
          <% end %>
        </div>
      </div>
    </nav>
    <main role="main" class="container mx-auto">
      <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>
      <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>
      <%= @inner_content %>
    </main>

lib/pcpb_web/templates/layout/live.html.leex
<script>
  const setup = () => {
    return {
      loading: true,
      isSidebarOpen: false,
      toggleSidbarMenu() {
        console.log('xd')
        this.isSidebarOpen = !this.isSidebarOpen
      },
      isSettingsPanelOpen: false,
      isSearchBoxOpen: false,
    }
  }
</script>
<div class="flex h-full max-h-full min-w-full overflow-hidden"  x-data="setup()">
  <%= render "sidebar.html", socket: @socket %>
  <div class="flex-grow max-h-screen text-gray-900 bg-white" :class="{'': !isSidebarOpen}">
    <div class="flex items-center h-16 text-center align-middle">
      <button @click="toggleSidbarMenu()" class="p-2 rounded-md focus:outline-none sm:hidden" :class="{'hidden': isSidebarOpen}">
        <svg
          class="w-4 h-4 text-gray-600"
          :class="{'hidden': isSidebarOpen}"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 5l7 7-7 7M5 5l7 7-7 7" />
        </svg>
      </button>
      <%= live_patch "System Builder", to: Routes.product_index_path(@socket, :index), class: nav_classes() %>
      <%= live_patch "Products", to: Routes.product_index_path(@socket, :index), class: nav_classes() %>
      <ul class="hidden">
        <%= for product <- PcpbWeb.LayoutView.products_map do %>
          <li>
            <%= live_patch product.name, to: Routes.product_index_path(@socket, :index, product.atom), class: nav_classes() %>
          </li>
        <% end %>
      </ul>
      <div class="flex-1"></div>
      <%= if @user do %>
        <a class="<%= nav_classes() %>"><%= @user.username %></a>
      <% else %>
        <%= live_patch "Login", to: Routes.login_path(@socket, :new), class: nav_classes() %>
        <%= live_patch "Register", to: Routes.signup_path(@socket, :new), class: nav_classes() %>
      <% end %>
    </div>
    <hr class="p-0 m-0"/>

    <main role="main" class="h-full overflow-y-auto bg-gray-100">
      <p class="alert alert-info" role="alert"
            phx-click="lv:clear-flash"
            phx-value-key="info"><%= live_flash(@flash, :info) %></p>
      <p class="alert alert-danger" role="alert"
            phx-click="lv:clear-flash"
            phx-value-key="error"><%= live_flash(@flash, :error) %></p>
      <div class="overflow-y-auto">
        <%= @inner_content %>
      </div>
    </main>
  </div>
</div>

lib/pcpb_web/templates/layout/root.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Pcpb", suffix: " · PCPB" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.6.11/dist/css/uikit.min.css" />
    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.6.11/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.6.11/dist/js/uikit-icons.min.js"></script>
  </head>
  <body class="h-screen" style="background: #edf2f7;">
    <%= @inner_content %>
  </body>
</html>

lib/pcpb_web/templates/layout/sidebar.html copy.leex
  <div
    x-show.in.out.opacity="isSidebarOpen"
    class="fixed inset-0 z-10 bg-black bg-opacity-20 lg:hidden"
    style="backdrop-filter: blur(14px); -webkit-backdrop-filter: blur(14px)"
></div>
<aside
  x-transition:enter="transition transform duration-300"
  x-transition:enter-start="-translate-x-full opacity-30  ease-in"
  x-transition:enter-end="translate-x-0 opacity-100 ease-out"
  x-transition:leave="transition transform duration-300"
  x-transition:leave-start="translate-x-0 opacity-100 ease-out"
  x-transition:leave-end="-translate-x-full opacity-0 ease-in"
  class="fixed inset-y-0 z-30 flex flex-col flex-shrink-0 w-64 max-h-screen min-h-screen overflow-hidden transition-all transform bg-white border-r shadow-lg lg:z-auto lg:static lg:shadow-none"
  :class="{'-translate-x-full lg:translate-x-0 lg:w-20': !isSidebarOpen}"
>
  <!-- sidebar header -->
  <div class="flex items-center justify-between flex-shrink-0 p-2" :class="{'lg:justify-center': !isSidebarOpen}">
    <span class="p-2 text-xl font-semibold leading-8 tracking-wider uppercase whitespace-nowrap">
      <span :class="{'lg:hidden': isSidebarOpen}">PCPB</span>
      <span :class="{'lg:hidden': !isSidebarOpen}">PCPartBuilder</span>
    </span>
    <button @click="toggleSidbarMenu()" class="p-2 rounded-md lg:hidden">
      <svg
            class="w-6 h-6 text-gray-600"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
      </svg>
    </button>
  </div>
  <!-- Sidebar links -->
  <nav class="flex-1 overflow-hidden hover:overflow-y-auto">
    <ul class="p-2 overflow-hidden">
      <li>
        <a
        href="#"
        class="flex items-center p-2 space-x-2 rounded-md hover:bg-gray-100"
        :class="{'justify-center': !isSidebarOpen}">
          <span>
            <svg
                  class="w-6 h-6 text-gray-400"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
              <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
                  />
              </svg>
            </span>
            <span :class="{ 'lg:hidden': !isSidebarOpen }">Dashboard</span>
          </a>
        </li>
        <!-- Sidebar Links... -->
      </ul>
    </nav>
    <!-- Sidebar footer -->
    <div class="flex-shrink-0 p-2 border-t max-h-14">
      <button
          class="flex items-center justify-center w-full px-4 py-2 space-x-1 font-medium tracking-wider uppercase bg-gray-100 border rounded-md focus:outline-none focus:ring"
        >
        <span>
          <svg
              class="w-6 h-6"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
            <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"
              />
            </svg>
          </span>
          <span :class="{'lg:hidden': !isSidebarOpen}"> Logout </span>
        </button>
      </div>
    </aside>

lib/pcpb_web/templates/layout/sidebar.html.leex
  <div
    x-show.in.out.opacity="isSidebarOpen"
    class="fixed inset-0 z-10 bg-black bg-opacity-20 lg:hidden"
    style="backdrop-filter: blur(14px); -webkit-backdrop-filter: blur(14px)"
></div>
<aside
  x-transition:enter="transition transform duration-300"
  x-transition:enter-start="-translate-x-full opacity-30  ease-in"
  x-transition:enter-end="translate-x-0 opacity-100 ease-out"
  x-transition:leave="transition transform duration-300"
  x-transition:leave-start="translate-x-0 opacity-100 ease-out"
  x-transition:leave-end="-translate-x-full opacity-0 ease-in"
  class="fixed inset-y-0 z-30 flex flex-col flex-shrink-0 max-h-screen min-h-screen overflow-hidden transition-all transform bg-white border-r shadow-lg w-54 lg:z-auto lg:static lg:shadow-none"
  :class="{'-translate-x-full lg:translate-x-0 w-24': !isSidebarOpen, 'col-span-2 w-54': isSidebarOpen}"
>
  <!-- sidebar header -->
  <div class="flex items-center justify-between flex-shrink-0 h-16" :class="{'lg:justify-center': !isSidebarOpen}">
    <span class="p-2 text-xl font-semibold leading-8 tracking-wider uppercase whitespace-nowrap">
      <%= live_patch to: Routes.page_path(@socket, :index), class: "hover:no-underline" do %>
        <span :class="{'lg:hidden text-pcpbblue': isSidebarOpen}"  x-show="!isSidebarOpen">PCPB</span>
        <span :class="{'lg:hidden text-pcpbblue': !isSidebarOpen}" x-show="isSidebarOpen">PCPartBuilder</span>
      <% end %>
      <button @click="toggleSidbarMenu()" class="p-2 rounded-md focus:outline-none">
        <svg
                  class="w-4 h-4 text-gray-600"
                  :class="{'transform transition-transform -rotate-180': isSidebarOpen}"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 5l7 7-7 7M5 5l7 7-7 7" />
        </svg>
      </button>
    </span>
  </div>
  <hr class="p-0 m-0"/>
  <!-- Sidebar links -->
  <nav class="flex-1 overflow-hidden hover:overflow-y-auto">
    <ul class="p-2 overflow-hidden">
      <li>
        <a
        href="#"
        class="flex items-center p-2 space-x-2 rounded-md hover:bg-gray-100"
        :class="{'justify-center': !isSidebarOpen}">
          <span>
            <svg
                  class="w-6 h-6 text-gray-400"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
              <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
                  />
              </svg>
            </span>
            <span :class="{ 'lg:hidden': !isSidebarOpen }">Dashboard</span>
          </a>
        </li>
        <!-- Sidebar Links... -->
      </ul>
    </nav>
    <!-- Sidebar footer -->
    <div class="flex-shrink-0 p-2 border-t max-h-14">
      <button
          class="flex items-center justify-center w-full px-4 py-2 space-x-1 font-medium tracking-wider uppercase bg-gray-100 border rounded-md focus:outline-none focus:ring"
        >
        <span>
          <svg
              class="w-6 h-6"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
            <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"
              />
            </svg>
          </span>
          <span :class="{'lg:hidden': !isSidebarOpen}"> Logout </span>
        </button>
      </div>
    </aside>